@echo off

setx POSTGRES_USERNAME "KENDI_KULLANICI_ADINI_YAZ"
setx POSTGRES_PASSWORD "KENDI_PAROLANI_YAZ"

setx JAVA_SECRETKEY "KENDI_SECRRET_ANAHTARINI_YAZ"
setx JAVA_ISSUER "KENDI_ISSUER_YAZ"

setx GIT_CONFIG_PROJECT "Kendin yaz"
setx GIT_USERNAME "Kendin yaz"
setx GIT_TOKEN_KEY "Kendin yaz"

